import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

// eslint-config-next 15 still ships only an eslintrc-style config, so flat config reaches it
// through the compatibility bridge. This is what create-next-app itself generates.
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  // next-env.d.ts is generated by Next on every build and must not be hand-edited.
  { ignores: [".next/**", "node_modules/**", "src/api/generated/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
